nature_names = {
    "NATURE_HARDY": "Hardy",
    "NATURE_LONELY": "Lonely",
    "NATURE_BRAVE": "Brave",
    "NATURE_ADAMANT": "Adamant",
    "NATURE_NAUGHTY": "Naughty",
    "NATURE_BOLD": "Bold",
    "NATURE_DOCILE": "Docile",
    "NATURE_RELAXED": "Relaxed",
    "NATURE_IMPISH": "Impish",
    "NATURE_LAX": "Lax",
    "NATURE_TIMID": "Timid",
    "NATURE_HASTY": "Hasty",
    "NATURE_SERIOUS": "Serious",
    "NATURE_JOLLY": "Jolly",
    "NATURE_NAIVE": "Naive",
    "NATURE_MODEST": "Modest",
    "NATURE_MILD": "Mild",
    "NATURE_QUIET": "Quiet",
    "NATURE_BASHFUL": "Bashful",
    "NATURE_RASH": "Rash",
    "NATURE_CALM": "Calm",
    "NATURE_GENTLE": "Gentle",
    "NATURE_SASSY": "Sassy",
    "NATURE_CAREFUL": "Careful",
    "NATURE_QUIRKY": "Quirky",
}

status_names = {
    "STATUS1_NONE": "None",
    "STATUS1_SLEEP": "Sleep",
    "STATUS1_POISON": "Poison",
    "STATUS1_BURN": "Burn",
    "STATUS1_FREEZE": "Freeze",
    "STATUS1_PARALYSIS": "Paralysis",
    "STATUS1_TOXIC_POISON": "Toxic Poison",
}

status_names = {
    "STATUS1_NONE": "None",
    "STATUS1_SLEEP": "Sleep",
    "STATUS1_POISON": "Poisoned",
    "STATUS1_BURN": "Burned",
    "STATUS1_FREEZE": "Freeze",
    "STATUS1_PARALYSIS": "Paralysis",
    "STATUS1_TOXIC_POISON": "Toxic Poison",
}

tera_types = {
    "TYPE_NORMAL": "Normal",
    "TYPE_FIGHTING": "Fighting",
    "TYPE_FLYING": "Flying",
    "TYPE_POISON": "Poison",
    "TYPE_GROUND": "Ground",
    "TYPE_ROCK": "Rock",
    "TYPE_BUG": "Bug",
    "TYPE_GHOST": "Ghost",
    "TYPE_STEEL": "Steel",
    "TYPE_FIRE": "Fire",
    "TYPE_WATER": "Water",
    "TYPE_GRASS": "Grass",
    "TYPE_ELECTRIC": "Electric",
    "TYPE_PSYCHIC": "Psychic",
    "TYPE_ICE": "Ice",
    "TYPE_DRAGON": "Dragon",
    "TYPE_DARK": "Dark",
    "TYPE_FAIRY": "Fairy",
    "TYPE_STELLAR": "Stellar",
}
